# PARAM_METADATA maps each SPSA parameter to (name, min_val, max_val, default_val, type, perturb_scale)
PARAM_METADATA = [
    # ROUTING
    ("ROUTING_SHALLOW_RATIO", 0.0, 0.3, 0.222793302471067, float, 1.0),
    ("ROUTING_MEDIUM_RATIO", 0.0, 0.5, 0.371234896865288, float, 1.0),
    # ROOT
    ("ROOT_MIN_ENTROPY", 0, 1027080, 185329, int, 1.0),
    ("ROOT_GAC_MIN_ENTROPY", 0, 1027080, 78489, int, 1.0),
    ("ROOT_CONSTR_MIN_ENTROPY", 0, 1027080, 55089, int, 1.0),
    ("ROOT_PERIOD_COEF_SQRT", 0, 100, 17, int, 1.0),
    ("ROOT_PERIOD_COEF_INV", 0, 100, 5, int, 1.0),
    ("ROOT_PERIOD_COEF_UNSET", 0, 100, 5, int, 1.0),
    # SHALLOW
    ("SHALLOW_MIN_ENTROPY", 0, 1027080, 350722, int, 1.0),
    ("SHALLOW_GAC_MIN_ENTROPY", 0, 1027080, 184831, int, 1.0),
    ("SHALLOW_CONSTR_MIN_ENTROPY", 0, 1027080, 419280, int, 1.0),
    ("SHALLOW_PERIOD_COEF_SQRT", 0, 100, 0, int, 1.0),
    ("SHALLOW_PERIOD_COEF_INV", 0, 100, 0, int, 1.0),
    ("SHALLOW_PERIOD_COEF_UNSET", 0, 100, 0, int, 1.0),
    # MEDIUM
    ("MEDIUM_MIN_ENTROPY", 0, 1027080, 205091, int, 1.0),
    ("MEDIUM_GAC_MIN_ENTROPY", 0, 1027080, 81106, int, 1.0),
    ("MEDIUM_CONSTR_MIN_ENTROPY", 0, 1027080, 222636, int, 1.0),
    ("MEDIUM_PERIOD_COEF_SQRT", 0, 100, 1, int, 1.0),
    ("MEDIUM_PERIOD_COEF_INV", 0, 100, 1, int, 1.0),
    ("MEDIUM_PERIOD_COEF_UNSET", 0, 100, 4, int, 1.0),
    # DEEP
    ("DEEP_MIN_ENTROPY", 0, 1027080, 183314, int, 1.0),
    ("DEEP_GAC_MIN_ENTROPY", 0, 1027080, 248894, int, 1.0),
    ("DEEP_CONSTR_MIN_ENTROPY", 0, 1027080, 553039, int, 1.0),
    ("DEEP_PERIOD_COEF_SQRT", 0, 100, 17, int, 1.0),
    ("DEEP_PERIOD_COEF_INV", 0, 100, 4, int, 1.0),
    ("DEEP_PERIOD_COEF_UNSET", 0, 100, 4, int, 1.0),
    # NODE SELECT SELECTIVITY ROUTING
    ("SEL_PERIOD_COEF_SQRT", 0, 100, 3, int, 1.0),
    ("SEL_PERIOD_COEF_INV", 0, 100, 8, int, 1.0),
    # LOOKAHEAD DOWNGRADE FRACTIONS
    ("ROOT_LOOKAHEAD_DOWNGRADE_FRACTION", 0.0, 1.0, 0.0101000994871915, float, 1.0),
    ("SHALLOW_LOOKAHEAD_DOWNGRADE_FRACTION", 0.0, 1.0, 0.00879761616511986, float, 1.0),
    ("MEDIUM_LOOKAHEAD_DOWNGRADE_FRACTION", 0.0, 1.0, 0.00124409108963121, float, 1.0),
    ("DEEP_LOOKAHEAD_DOWNGRADE_FRACTION", 0.0, 1.0, 0.0926045184018191, float, 1.0),
    # ROOT LOCAL/GLOBAL BOUNDS
    ("ROOT_GAC_LOCAL_MIN_UNSET", 0.0, 1.0, 0.26429861325863, float, 3.0),
    ("ROOT_GAC_LOCAL_MAX_UNSET", 0.0, 1.0, 0.871974739373579, float, 3.0),
    ("ROOT_GAC_GLOBAL_MIN_ENTROPY", 0, 1027080, 531343, int, 1.0),
    ("ROOT_CONSTR_LOCAL_MIN_UNSET", 0.0, 1.0, 0.263387426980487, float, 3.0),
    ("ROOT_CONSTR_LOCAL_MAX_UNSET", 0.0, 1.0, 0.894186070844627, float, 3.0),
    ("ROOT_CONSTR_GLOBAL_MIN_ENTROPY", 0, 1027080, 568387, int, 1.0),
    ("ROOT_LOOKAHEAD_GAC_LOCAL_MIN_UNSET", 0.0, 1.0, 0.243315999107488, float, 3.0),
    ("ROOT_LOOKAHEAD_GAC_LOCAL_MAX_UNSET", 0.0, 1.0, 0.871298837386777, float, 3.0),
    ("ROOT_LOOKAHEAD_GAC_GLOBAL_MIN_ENTROPY", 0, 1027080, 617097, int, 1.0),
    ("ROOT_LOOKAHEAD_CONSTR_LOCAL_MIN_UNSET", 0.0, 1.0, 0.237709105267698, float, 3.0),
    ("ROOT_LOOKAHEAD_CONSTR_LOCAL_MAX_UNSET", 0.0, 1.0, 0.881122993251411, float, 3.0),
    ("ROOT_LOOKAHEAD_CONSTR_GLOBAL_MIN_ENTROPY", 0, 1027080, 466491, int, 1.0),
    # SHALLOW LOCAL/GLOBAL BOUNDS
    ("SHALLOW_GAC_LOCAL_MIN_UNSET", 0.0, 1.0, 0.244809018867735, float, 3.0),
    ("SHALLOW_GAC_LOCAL_MAX_UNSET", 0.0, 1.0, 0.867324160155205, float, 3.0),
    ("SHALLOW_GAC_GLOBAL_MIN_ENTROPY", 0, 1027080, 594571, int, 1.0),
    ("SHALLOW_CONSTR_LOCAL_MIN_UNSET", 0.0, 1.0, 0.274282359150116, float, 3.0),
    ("SHALLOW_CONSTR_LOCAL_MAX_UNSET", 0.0, 1.0, 0.910160431254728, float, 3.0),
    ("SHALLOW_CONSTR_GLOBAL_MIN_ENTROPY", 0, 1027080, 484504, int, 1.0),
    ("SHALLOW_LOOKAHEAD_GAC_LOCAL_MIN_UNSET", 0.0, 1.0, 0.234576576106668, float, 3.0),
    ("SHALLOW_LOOKAHEAD_GAC_LOCAL_MAX_UNSET", 0.0, 1.0, 0.874388471886849, float, 3.0),
    ("SHALLOW_LOOKAHEAD_GAC_GLOBAL_MIN_ENTROPY", 0, 1027080, 661205, int, 1.0),
    ("SHALLOW_LOOKAHEAD_CONSTR_LOCAL_MIN_UNSET", 0.0, 1.0, 0.252382397323835, float, 3.0),
    ("SHALLOW_LOOKAHEAD_CONSTR_LOCAL_MAX_UNSET", 0.0, 1.0, 0.928500496012114, float, 3.0),
    ("SHALLOW_LOOKAHEAD_CONSTR_GLOBAL_MIN_ENTROPY", 0, 1027080, 382149, int, 1.0),
    # MEDIUM LOCAL/GLOBAL BOUNDS
    ("MEDIUM_GAC_LOCAL_MIN_UNSET", 0.0, 1.0, 0.266914750278902, float, 3.0),
    ("MEDIUM_GAC_LOCAL_MAX_UNSET", 0.0, 1.0, 0.871921770004992, float, 3.0),
    ("MEDIUM_GAC_GLOBAL_MIN_ENTROPY", 0, 1027080, 568513, int, 1.0),
    ("MEDIUM_CONSTR_LOCAL_MIN_UNSET", 0.0, 1.0, 0.252619574540004, float, 3.0),
    ("MEDIUM_CONSTR_LOCAL_MAX_UNSET", 0.0, 1.0, 0.862497217218792, float, 3.0),
    ("MEDIUM_CONSTR_GLOBAL_MIN_ENTROPY", 0, 1027080, 390355, int, 1.0),
    ("MEDIUM_LOOKAHEAD_GAC_LOCAL_MIN_UNSET", 0.0, 1.0, 0.243223106053211, float, 3.0),
    ("MEDIUM_LOOKAHEAD_GAC_LOCAL_MAX_UNSET", 0.0, 1.0, 0.877143165724505, float, 3.0),
    ("MEDIUM_LOOKAHEAD_GAC_GLOBAL_MIN_ENTROPY", 0, 1027080, 526444, int, 1.0),
    ("MEDIUM_LOOKAHEAD_CONSTR_LOCAL_MIN_UNSET", 0.0, 1.0, 0.253783635285449, float, 3.0),
    ("MEDIUM_LOOKAHEAD_CONSTR_LOCAL_MAX_UNSET", 0.0, 1.0, 0.880296986365227, float, 3.0),
    ("MEDIUM_LOOKAHEAD_CONSTR_GLOBAL_MIN_ENTROPY", 0, 1027080, 523242, int, 1.0),
    # DEEP LOCAL/GLOBAL BOUNDS
    ("DEEP_GAC_LOCAL_MIN_UNSET", 0.0, 1.0, 0.266661339259724, float, 3.0),
    ("DEEP_GAC_LOCAL_MAX_UNSET", 0.0, 1.0, 0.868711152093341, float, 3.0),
    ("DEEP_GAC_GLOBAL_MIN_ENTROPY", 0, 1027080, 487465, int, 1.0),
    ("DEEP_CONSTR_LOCAL_MIN_UNSET", 0.0, 1.0, 0.252073368050884, float, 3.0),
    ("DEEP_CONSTR_LOCAL_MAX_UNSET", 0.0, 1.0, 0.877144826285916, float, 3.0),
    ("DEEP_CONSTR_GLOBAL_MIN_ENTROPY", 0, 1027080, 458252, int, 1.0),
    ("DEEP_LOOKAHEAD_GAC_LOCAL_MIN_UNSET", 0.0, 1.0, 0.244984853085172, float, 3.0),
    ("DEEP_LOOKAHEAD_GAC_LOCAL_MAX_UNSET", 0.0, 1.0, 0.871691056569888, float, 3.0),
    ("DEEP_LOOKAHEAD_GAC_GLOBAL_MIN_ENTROPY", 0, 1027080, 422238, int, 1.0),
    ("DEEP_LOOKAHEAD_CONSTR_LOCAL_MIN_UNSET", 0.0, 1.0, 0.244327803858185, float, 3.0),
    ("DEEP_LOOKAHEAD_CONSTR_LOCAL_MAX_UNSET", 0.0, 1.0, 0.869366448077845, float, 3.0),
    ("DEEP_LOOKAHEAD_CONSTR_GLOBAL_MIN_ENTROPY", 0, 1027080, 533204, int, 1.0),
]

# PARAMETER_MAPPING maps each SPSA parameter to (C_filepath, C_variable_name, type)
PARAMETER_MAPPING = {
    # ROUTING
    "ROUTING_SHALLOW_RATIO": ("src/prune_strat_routing.c", "g_routing_shallow_ratio", "double"),
    "ROUTING_MEDIUM_RATIO": ("src/prune_strat_routing.c", "g_routing_medium_ratio", "double"),
    # ROOT
    "ROOT_MIN_ENTROPY": ("src/prune_strat_root.c", "g_min_entropy_threshold", "int"),
    "ROOT_GAC_MIN_ENTROPY": ("src/prune_strat_root.c", "g_gac_min_entropy", "int"),
    "ROOT_CONSTR_MIN_ENTROPY": ("src/prune_strat_root.c", "g_constr_min_entropy", "int"),
    "ROOT_PERIOD_COEF_SQRT": ("src/prune_strat_root.c", "g_period_coef_sqrt", "int"),
    "ROOT_PERIOD_COEF_INV": ("src/prune_strat_root.c", "g_period_coef_inv", "int"),
    "ROOT_PERIOD_COEF_UNSET": ("src/prune_strat_root.c", "g_period_coef_unset", "int"),
    # SHALLOW
    "SHALLOW_MIN_ENTROPY": ("src/prune_strat_shallow.c", "g_min_entropy_threshold", "int"),
    "SHALLOW_GAC_MIN_ENTROPY": ("src/prune_strat_shallow.c", "g_gac_min_entropy", "int"),
    "SHALLOW_CONSTR_MIN_ENTROPY": ("src/prune_strat_shallow.c", "g_constr_min_entropy", "int"),
    "SHALLOW_PERIOD_COEF_SQRT": ("src/prune_strat_shallow.c", "g_period_coef_sqrt", "int"),
    "SHALLOW_PERIOD_COEF_INV": ("src/prune_strat_shallow.c", "g_period_coef_inv", "int"),
    "SHALLOW_PERIOD_COEF_UNSET": ("src/prune_strat_shallow.c", "g_period_coef_unset", "int"),
    # MEDIUM
    "MEDIUM_MIN_ENTROPY": ("src/prune_strat_medium.c", "g_min_entropy_threshold", "int"),
    "MEDIUM_GAC_MIN_ENTROPY": ("src/prune_strat_medium.c", "g_gac_min_entropy", "int"),
    "MEDIUM_CONSTR_MIN_ENTROPY": ("src/prune_strat_medium.c", "g_constr_min_entropy", "int"),
    "MEDIUM_PERIOD_COEF_SQRT": ("src/prune_strat_medium.c", "g_period_coef_sqrt", "int"),
    "MEDIUM_PERIOD_COEF_INV": ("src/prune_strat_medium.c", "g_period_coef_inv", "int"),
    "MEDIUM_PERIOD_COEF_UNSET": ("src/prune_strat_medium.c", "g_period_coef_unset", "int"),
    # DEEP
    "DEEP_MIN_ENTROPY": ("src/prune_strat_deep.c", "g_min_entropy_threshold", "int"),
    "DEEP_GAC_MIN_ENTROPY": ("src/prune_strat_deep.c", "g_gac_min_entropy", "int"),
    "DEEP_CONSTR_MIN_ENTROPY": ("src/prune_strat_deep.c", "g_constr_min_entropy", "int"),
    "DEEP_PERIOD_COEF_SQRT": ("src/prune_strat_deep.c", "g_period_coef_sqrt", "int"),
    "DEEP_PERIOD_COEF_INV": ("src/prune_strat_deep.c", "g_period_coef_inv", "int"),
    "DEEP_PERIOD_COEF_UNSET": ("src/prune_strat_deep.c", "g_period_coef_unset", "int"),
    # SELECTIVITY
    "SEL_PERIOD_COEF_SQRT": ("src/sel_strat_routing.c", "g_sel_period_coef_sqrt", "int"),
    "SEL_PERIOD_COEF_INV": ("src/sel_strat_routing.c", "g_sel_period_coef_inv", "int"),
    # LOOKAHEAD DOWNGRADE FRACTIONS
    "ROOT_LOOKAHEAD_DOWNGRADE_FRACTION": ("src/prune_strat_root.c", "g_lookahead_downgrade_fraction", "double"),
    "SHALLOW_LOOKAHEAD_DOWNGRADE_FRACTION": ("src/prune_strat_shallow.c", "g_lookahead_downgrade_fraction", "double"),
    "MEDIUM_LOOKAHEAD_DOWNGRADE_FRACTION": ("src/prune_strat_medium.c", "g_lookahead_downgrade_fraction", "double"),
    "DEEP_LOOKAHEAD_DOWNGRADE_FRACTION": ("src/prune_strat_deep.c", "g_lookahead_downgrade_fraction", "double"),
    # ROOT LOCAL/GLOBAL BOUNDS
    "ROOT_GAC_LOCAL_MIN_UNSET": ("src/prune_strat_root.c", "g_gac_local_min_unset", "double"),
    "ROOT_GAC_LOCAL_MAX_UNSET": ("src/prune_strat_root.c", "g_gac_local_max_unset", "double"),
    "ROOT_GAC_GLOBAL_MIN_ENTROPY": ("src/prune_strat_root.c", "g_gac_global_min_entropy", "int"),
    "ROOT_CONSTR_LOCAL_MIN_UNSET": ("src/prune_strat_root.c", "g_constr_local_min_unset", "double"),
    "ROOT_CONSTR_LOCAL_MAX_UNSET": ("src/prune_strat_root.c", "g_constr_local_max_unset", "double"),
    "ROOT_CONSTR_GLOBAL_MIN_ENTROPY": ("src/prune_strat_root.c", "g_constr_global_min_entropy", "int"),
    "ROOT_LOOKAHEAD_GAC_LOCAL_MIN_UNSET": ("src/prune_strat_root.c", "g_lookahead_gac_local_min_unset", "double"),
    "ROOT_LOOKAHEAD_GAC_LOCAL_MAX_UNSET": ("src/prune_strat_root.c", "g_lookahead_gac_local_max_unset", "double"),
    "ROOT_LOOKAHEAD_GAC_GLOBAL_MIN_ENTROPY": ("src/prune_strat_root.c", "g_lookahead_gac_global_min_entropy", "int"),
    "ROOT_LOOKAHEAD_CONSTR_LOCAL_MIN_UNSET": ("src/prune_strat_root.c", "g_lookahead_constr_local_min_unset", "double"),
    "ROOT_LOOKAHEAD_CONSTR_LOCAL_MAX_UNSET": ("src/prune_strat_root.c", "g_lookahead_constr_local_max_unset", "double"),
    "ROOT_LOOKAHEAD_CONSTR_GLOBAL_MIN_ENTROPY": ("src/prune_strat_root.c", "g_lookahead_constr_global_min_entropy", "int"),
    # SHALLOW LOCAL/GLOBAL BOUNDS
    "SHALLOW_GAC_LOCAL_MIN_UNSET": ("src/prune_strat_shallow.c", "g_gac_local_min_unset", "double"),
    "SHALLOW_GAC_LOCAL_MAX_UNSET": ("src/prune_strat_shallow.c", "g_gac_local_max_unset", "double"),
    "SHALLOW_GAC_GLOBAL_MIN_ENTROPY": ("src/prune_strat_shallow.c", "g_gac_global_min_entropy", "int"),
    "SHALLOW_CONSTR_LOCAL_MIN_UNSET": ("src/prune_strat_shallow.c", "g_constr_local_min_unset", "double"),
    "SHALLOW_CONSTR_LOCAL_MAX_UNSET": ("src/prune_strat_shallow.c", "g_constr_local_max_unset", "double"),
    "SHALLOW_CONSTR_GLOBAL_MIN_ENTROPY": ("src/prune_strat_shallow.c", "g_constr_global_min_entropy", "int"),
    "SHALLOW_LOOKAHEAD_GAC_LOCAL_MIN_UNSET": ("src/prune_strat_shallow.c", "g_lookahead_gac_local_min_unset", "double"),
    "SHALLOW_LOOKAHEAD_GAC_LOCAL_MAX_UNSET": ("src/prune_strat_shallow.c", "g_lookahead_gac_local_max_unset", "double"),
    "SHALLOW_LOOKAHEAD_GAC_GLOBAL_MIN_ENTROPY": ("src/prune_strat_shallow.c", "g_lookahead_gac_global_min_entropy", "int"),
    "SHALLOW_LOOKAHEAD_CONSTR_LOCAL_MIN_UNSET": ("src/prune_strat_shallow.c", "g_lookahead_constr_local_min_unset", "double"),
    "SHALLOW_LOOKAHEAD_CONSTR_LOCAL_MAX_UNSET": ("src/prune_strat_shallow.c", "g_lookahead_constr_local_max_unset", "double"),
    "SHALLOW_LOOKAHEAD_CONSTR_GLOBAL_MIN_ENTROPY": ("src/prune_strat_shallow.c", "g_lookahead_constr_global_min_entropy", "int"),
    # MEDIUM LOCAL/GLOBAL BOUNDS
    "MEDIUM_GAC_LOCAL_MIN_UNSET": ("src/prune_strat_medium.c", "g_gac_local_min_unset", "double"),
    "MEDIUM_GAC_LOCAL_MAX_UNSET": ("src/prune_strat_medium.c", "g_gac_local_max_unset", "double"),
    "MEDIUM_GAC_GLOBAL_MIN_ENTROPY": ("src/prune_strat_medium.c", "g_gac_global_min_entropy", "int"),
    "MEDIUM_CONSTR_LOCAL_MIN_UNSET": ("src/prune_strat_medium.c", "g_constr_local_min_unset", "double"),
    "MEDIUM_CONSTR_LOCAL_MAX_UNSET": ("src/prune_strat_medium.c", "g_constr_local_max_unset", "double"),
    "MEDIUM_CONSTR_GLOBAL_MIN_ENTROPY": ("src/prune_strat_medium.c", "g_constr_global_min_entropy", "int"),
    "MEDIUM_LOOKAHEAD_GAC_LOCAL_MIN_UNSET": ("src/prune_strat_medium.c", "g_lookahead_gac_local_min_unset", "double"),
    "MEDIUM_LOOKAHEAD_GAC_LOCAL_MAX_UNSET": ("src/prune_strat_medium.c", "g_lookahead_gac_local_max_unset", "double"),
    "MEDIUM_LOOKAHEAD_GAC_GLOBAL_MIN_ENTROPY": ("src/prune_strat_medium.c", "g_lookahead_gac_global_min_entropy", "int"),
    "MEDIUM_LOOKAHEAD_CONSTR_LOCAL_MIN_UNSET": ("src/prune_strat_medium.c", "g_lookahead_constr_local_min_unset", "double"),
    "MEDIUM_LOOKAHEAD_CONSTR_LOCAL_MAX_UNSET": ("src/prune_strat_medium.c", "g_lookahead_constr_local_max_unset", "double"),
    "MEDIUM_LOOKAHEAD_CONSTR_GLOBAL_MIN_ENTROPY": ("src/prune_strat_medium.c", "g_lookahead_constr_global_min_entropy", "int"),
    # DEEP LOCAL/GLOBAL BOUNDS
    "DEEP_GAC_LOCAL_MIN_UNSET": ("src/prune_strat_deep.c", "g_gac_local_min_unset", "double"),
    "DEEP_GAC_LOCAL_MAX_UNSET": ("src/prune_strat_deep.c", "g_gac_local_max_unset", "double"),
    "DEEP_GAC_GLOBAL_MIN_ENTROPY": ("src/prune_strat_deep.c", "g_gac_global_min_entropy", "int"),
    "DEEP_CONSTR_LOCAL_MIN_UNSET": ("src/prune_strat_deep.c", "g_constr_local_min_unset", "double"),
    "DEEP_CONSTR_LOCAL_MAX_UNSET": ("src/prune_strat_deep.c", "g_constr_local_max_unset", "double"),
    "DEEP_CONSTR_GLOBAL_MIN_ENTROPY": ("src/prune_strat_deep.c", "g_constr_global_min_entropy", "int"),
    "DEEP_LOOKAHEAD_GAC_LOCAL_MIN_UNSET": ("src/prune_strat_deep.c", "g_lookahead_gac_local_min_unset", "double"),
    "DEEP_LOOKAHEAD_GAC_LOCAL_MAX_UNSET": ("src/prune_strat_deep.c", "g_lookahead_gac_local_max_unset", "double"),
    "DEEP_LOOKAHEAD_GAC_GLOBAL_MIN_ENTROPY": ("src/prune_strat_deep.c", "g_lookahead_gac_global_min_entropy", "int"),
    "DEEP_LOOKAHEAD_CONSTR_LOCAL_MIN_UNSET": ("src/prune_strat_deep.c", "g_lookahead_constr_local_min_unset", "double"),
    "DEEP_LOOKAHEAD_CONSTR_LOCAL_MAX_UNSET": ("src/prune_strat_deep.c", "g_lookahead_constr_local_max_unset", "double"),
    "DEEP_LOOKAHEAD_CONSTR_GLOBAL_MIN_ENTROPY": ("src/prune_strat_deep.c", "g_lookahead_constr_global_min_entropy", "int"),
}

# PARAM_CONSTRAINTS defines linear constraints between parameters.
# Format: (param_min_name, param_max_name, eps)
# enforces: physical_value(param_min_name) <= physical_value(param_max_name) + eps
PARAM_CONSTRAINTS = [
    # ROOT
    ("ROOT_GAC_LOCAL_MIN_UNSET", "ROOT_GAC_LOCAL_MAX_UNSET", 0.05),
    ("ROOT_CONSTR_LOCAL_MIN_UNSET", "ROOT_CONSTR_LOCAL_MAX_UNSET", 0.05),
    ("ROOT_LOOKAHEAD_GAC_LOCAL_MIN_UNSET", "ROOT_LOOKAHEAD_GAC_LOCAL_MAX_UNSET", 0.05),
    ("ROOT_LOOKAHEAD_CONSTR_LOCAL_MIN_UNSET", "ROOT_LOOKAHEAD_CONSTR_LOCAL_MAX_UNSET", 0.05),
    # SHALLOW
    ("SHALLOW_GAC_LOCAL_MIN_UNSET", "SHALLOW_GAC_LOCAL_MAX_UNSET", 0.05),
    ("SHALLOW_CONSTR_LOCAL_MIN_UNSET", "SHALLOW_CONSTR_LOCAL_MAX_UNSET", 0.05),
    ("SHALLOW_LOOKAHEAD_GAC_LOCAL_MIN_UNSET", "SHALLOW_LOOKAHEAD_GAC_LOCAL_MAX_UNSET", 0.05),
    ("SHALLOW_LOOKAHEAD_CONSTR_LOCAL_MIN_UNSET", "SHALLOW_LOOKAHEAD_CONSTR_LOCAL_MAX_UNSET", 0.05),
    # MEDIUM
    ("MEDIUM_GAC_LOCAL_MIN_UNSET", "MEDIUM_GAC_LOCAL_MAX_UNSET", 0.05),
    ("MEDIUM_CONSTR_LOCAL_MIN_UNSET", "MEDIUM_CONSTR_LOCAL_MAX_UNSET", 0.05),
    ("MEDIUM_LOOKAHEAD_GAC_LOCAL_MIN_UNSET", "MEDIUM_LOOKAHEAD_GAC_LOCAL_MAX_UNSET", 0.05),
    ("MEDIUM_LOOKAHEAD_CONSTR_LOCAL_MIN_UNSET", "MEDIUM_LOOKAHEAD_CONSTR_LOCAL_MAX_UNSET", 0.05),
    # DEEP
    ("DEEP_GAC_LOCAL_MIN_UNSET", "DEEP_GAC_LOCAL_MAX_UNSET", 0.05),
    ("DEEP_CONSTR_LOCAL_MIN_UNSET", "DEEP_CONSTR_LOCAL_MAX_UNSET", 0.05),
    ("DEEP_LOOKAHEAD_GAC_LOCAL_MIN_UNSET", "DEEP_LOOKAHEAD_GAC_LOCAL_MAX_UNSET", 0.05),
    ("DEEP_LOOKAHEAD_CONSTR_LOCAL_MIN_UNSET", "DEEP_LOOKAHEAD_CONSTR_LOCAL_MAX_UNSET", 0.05),
]
