# PARAM_METADATA maps each SPSA parameter to (name, min_val, max_val, default_val, type, perturb_scale)
PARAM_METADATA = [
    # ROUTING
    ("ROUTING_SHALLOW_RATIO", 0.0, 0.3, 0.21694617605868, float, 1.0),
    ("ROUTING_MEDIUM_RATIO", 0.0, 0.5, 0.34890330972895, float, 1.0),
    ("GLOBAL_ENTROPY_UNSET_BIAS", 100.0, 2000.0, 500.0, float, 1.0),
    # ROOT
    ("ROOT_MIN_ENTROPY", 0, 1027080, 78134, int, 1.0),
    ("ROOT_GAC_MIN_ENTROPY", 0, 1027080, 173236, int, 1.0),
    ("ROOT_CONSTR_MIN_ENTROPY", 0, 1027080, 60760, int, 1.0),
    ("ROOT_PERIOD_COEF_SCALE", 0.0, 100000.0, 4799.2167925152, float, 1.0),
    ("ROOT_PERIOD_COEF_UNSET", 0.0, 100.0, 1.5987496630714, float, 1.0),
    # SHALLOW
    ("SHALLOW_MIN_ENTROPY", 0, 1027080, 196199, int, 1.0),
    ("SHALLOW_GAC_MIN_ENTROPY", 0, 1027080, 176901, int, 1.0),
    ("SHALLOW_CONSTR_MIN_ENTROPY", 0, 1027080, 405447, int, 1.0),
    ("SHALLOW_PERIOD_COEF_SCALE", 0.0, 100000.0, 72.467005980998, float, 1.0),
    ("SHALLOW_PERIOD_COEF_UNSET", 0.0, 100.0, 1.6499213652034, float, 1.0),
    # MEDIUM
    ("MEDIUM_MIN_ENTROPY", 0, 1027080, 228598, int, 1.0),
    ("MEDIUM_GAC_MIN_ENTROPY", 0, 1027080, 16236, int, 1.0),
    ("MEDIUM_CONSTR_MIN_ENTROPY", 0, 1027080, 162306, int, 1.0),
    ("MEDIUM_PERIOD_COEF_SCALE", 0.0, 100000.0, 66.594298030099, float, 1.0),
    ("MEDIUM_PERIOD_COEF_UNSET", 0.0, 100.0, 1.9123654003116, float, 1.0),
    # DEEP
    ("DEEP_MIN_ENTROPY", 0, 1027080, 262010, int, 1.0),
    ("DEEP_GAC_MIN_ENTROPY", 0, 1027080, 263878, int, 1.0),
    ("DEEP_CONSTR_MIN_ENTROPY", 0, 1027080, 500036, int, 1.0),
    ("DEEP_PERIOD_COEF_SCALE", 0.0, 100000.0, 4575.6914627005, float, 1.0),
    ("DEEP_PERIOD_COEF_UNSET", 0.0, 100.0, 3.3094640267171, float, 1.0),
    # NODE SELECT SELECTIVITY ROUTING
    ("SEL_PERIOD_COEF_SQRT", 0.0, 100000.0, 9007.2492054366, float, 1.0),
    ("SEL_PERIOD_COEF_INV", 0.0, 100000.0, 15857.773828945, float, 1.0),
    # LOOKAHEAD DOWNGRADE FRACTIONS
    ("ROOT_LOOKAHEAD_DOWNGRADE_FRACTION", 0.0, 1.0, 0.46294416911457, float, 0.3),
    ("SHALLOW_LOOKAHEAD_DOWNGRADE_FRACTION", 0.0, 1.0, 0.29612090103214, float, 0.3),
    ("MEDIUM_LOOKAHEAD_DOWNGRADE_FRACTION", 0.0, 1.0, 0.18861364033551, float, 0.3),
    ("DEEP_LOOKAHEAD_DOWNGRADE_FRACTION", 0.0, 1.0, 0.29612, float, 0.3),
    # ROOT LOCAL/GLOBAL BOUNDS
    ("ROOT_GAC_LOCAL_MIN_ENTROPY", 0.0, 1.0, 0.26403984714856, float, 3.0),
    ("ROOT_GAC_LOCAL_MAX_ENTROPY", 0.0, 1.0, 0.86663709380776, float, 3.0),
    ("ROOT_GAC_GLOBAL_MIN_ENTROPY", 0, 1027080, 551936, int, 1.0),
    ("ROOT_CONSTR_LOCAL_MIN_ENTROPY", 0.0, 1.0, 0.25491863241256, float, 3.0),
    ("ROOT_CONSTR_LOCAL_MAX_ENTROPY", 0.0, 1.0, 0.91519577820637, float, 3.0),
    ("ROOT_CONSTR_GLOBAL_MIN_ENTROPY", 0, 1027080, 550744, int, 1.0),
    ("ROOT_LOOKAHEAD_GAC_LOCAL_MIN_ENTROPY", 0.0, 1.0, 0.25039325177129, float, 3.0),
    ("ROOT_LOOKAHEAD_GAC_LOCAL_MAX_ENTROPY", 0.0, 1.0, 0.87008838095546, float, 3.0),
    ("ROOT_LOOKAHEAD_GAC_GLOBAL_MIN_ENTROPY", 0, 1027080, 629680, int, 1.0),
    ("ROOT_LOOKAHEAD_CONSTR_LOCAL_MIN_ENTROPY", 0.0, 1.0, 0.23168816964554, float, 3.0),
    ("ROOT_LOOKAHEAD_CONSTR_LOCAL_MAX_ENTROPY", 0.0, 1.0, 0.88465119749469, float, 3.0),
    ("ROOT_LOOKAHEAD_CONSTR_GLOBAL_MIN_ENTROPY", 0, 1027080, 500103, int, 1.0),
    # SHALLOW LOCAL/GLOBAL BOUNDS
    ("SHALLOW_GAC_LOCAL_MIN_ENTROPY", 0.0, 1.0, 0.25127728658671, float, 3.0),
    ("SHALLOW_GAC_LOCAL_MAX_ENTROPY", 0.0, 1.0, 0.87573416830981, float, 3.0),
    ("SHALLOW_GAC_GLOBAL_MIN_ENTROPY", 0, 1027080, 650410, int, 1.0),
    ("SHALLOW_CONSTR_LOCAL_MIN_ENTROPY", 0.0, 1.0, 0.26639221323249, float, 3.0),
    ("SHALLOW_CONSTR_LOCAL_MAX_ENTROPY", 0.0, 1.0, 0.90501939952603, float, 3.0),
    ("SHALLOW_CONSTR_GLOBAL_MIN_ENTROPY", 0, 1027080, 455199, int, 1.0),
    ("SHALLOW_LOOKAHEAD_GAC_LOCAL_MIN_ENTROPY", 0.0, 1.0, 0.23654414722219, float, 3.0),
    ("SHALLOW_LOOKAHEAD_GAC_LOCAL_MAX_ENTROPY", 0.0, 1.0, 0.85744667676117, float, 3.0),
    ("SHALLOW_LOOKAHEAD_GAC_GLOBAL_MIN_ENTROPY", 0, 1027080, 719276, int, 1.0),
    ("SHALLOW_LOOKAHEAD_CONSTR_LOCAL_MIN_ENTROPY", 0.0, 1.0, 0.32295732577842, float, 3.0),
    ("SHALLOW_LOOKAHEAD_CONSTR_LOCAL_MAX_ENTROPY", 0.0, 1.0, 0.90415608054555, float, 3.0),
    ("SHALLOW_LOOKAHEAD_CONSTR_GLOBAL_MIN_ENTROPY", 0, 1027080, 571282, int, 1.0),
    # MEDIUM LOCAL/GLOBAL BOUNDS
    ("MEDIUM_GAC_LOCAL_MIN_ENTROPY", 0.0, 1.0, 0.24976692813905, float, 3.0),
    ("MEDIUM_GAC_LOCAL_MAX_ENTROPY", 0.0, 1.0, 0.88287424050584, float, 3.0),
    ("MEDIUM_GAC_GLOBAL_MIN_ENTROPY", 0, 1027080, 544680, int, 1.0),
    ("MEDIUM_CONSTR_LOCAL_MIN_ENTROPY", 0.0, 1.0, 0.2551881873664, float, 3.0),
    ("MEDIUM_CONSTR_LOCAL_MAX_ENTROPY", 0.0, 1.0, 0.85882035966809, float, 3.0),
    ("MEDIUM_CONSTR_GLOBAL_MIN_ENTROPY", 0, 1027080, 254698, int, 1.0),
    ("MEDIUM_LOOKAHEAD_GAC_LOCAL_MIN_ENTROPY", 0.0, 1.0, 0.24038403719693, float, 3.0),
    ("MEDIUM_LOOKAHEAD_GAC_LOCAL_MAX_ENTROPY", 0.0, 1.0, 0.86382652178173, float, 3.0),
    ("MEDIUM_LOOKAHEAD_GAC_GLOBAL_MIN_ENTROPY", 0, 1027080, 520076, int, 1.0),
    ("MEDIUM_LOOKAHEAD_CONSTR_LOCAL_MIN_ENTROPY", 0.0, 1.0, 0.25496670174914, float, 3.0),
    ("MEDIUM_LOOKAHEAD_CONSTR_LOCAL_MAX_ENTROPY", 0.0, 1.0, 0.8903038845368, float, 3.0),
    ("MEDIUM_LOOKAHEAD_CONSTR_GLOBAL_MIN_ENTROPY", 0, 1027080, 564625, int, 1.0),
    # DEEP LOCAL/GLOBAL BOUNDS
    ("DEEP_GAC_LOCAL_MIN_ENTROPY", 0.0, 1.0, 0.28536484980293, float, 3.0),
    ("DEEP_GAC_LOCAL_MAX_ENTROPY", 0.0, 1.0, 0.85827347117974, float, 3.0),
    ("DEEP_GAC_GLOBAL_MIN_ENTROPY", 0, 1027080, 525298, int, 1.0),
    ("DEEP_CONSTR_LOCAL_MIN_ENTROPY", 0.0, 1.0, 0.26697111246797, float, 3.0),
    ("DEEP_CONSTR_LOCAL_MAX_ENTROPY", 0.0, 1.0, 0.87844874301787, float, 3.0),
    ("DEEP_CONSTR_GLOBAL_MIN_ENTROPY", 0, 1027080, 446300, int, 1.0),
    ("DEEP_LOOKAHEAD_GAC_LOCAL_MIN_ENTROPY", 0.0, 1.0, 0.24417626618407, float, 3.0),
    ("DEEP_LOOKAHEAD_GAC_LOCAL_MAX_ENTROPY", 0.0, 1.0, 0.88571409502717, float, 3.0),
    ("DEEP_LOOKAHEAD_GAC_GLOBAL_MIN_ENTROPY", 0, 1027080, 407970, int, 1.0),
    ("DEEP_LOOKAHEAD_CONSTR_LOCAL_MIN_ENTROPY", 0.0, 1.0, 0.26981273291865, float, 3.0),
    ("DEEP_LOOKAHEAD_CONSTR_LOCAL_MAX_ENTROPY", 0.0, 1.0, 0.84642514552612, float, 3.0),
    ("DEEP_LOOKAHEAD_CONSTR_GLOBAL_MIN_ENTROPY", 0, 1027080, 488450, int, 1.0),
    # TIER MULTIPLIERS
    ("ROOT_PERIOD_TIER_MEDIUM_MULTIPLIER", 1.0, 10.0, 2.1524550822097, float, 1.0),
    ("ROOT_PERIOD_TIER_HEAVY_MULTIPLIER", 1.0, 20.0, 3.6488894122092, float, 1.0),
    ("SHALLOW_PERIOD_TIER_MEDIUM_MULTIPLIER", 1.0, 10.0, 1.9847541604479, float, 1.0),
    ("SHALLOW_PERIOD_TIER_HEAVY_MULTIPLIER", 1.0, 20.0, 3.8640836942421, float, 1.0),
    ("MEDIUM_PERIOD_TIER_MEDIUM_MULTIPLIER", 1.0, 10.0, 2.0979918709094, float, 1.0),
    ("MEDIUM_PERIOD_TIER_HEAVY_MULTIPLIER", 1.0, 20.0, 4.5322647052361, float, 1.0),
    ("DEEP_PERIOD_TIER_MEDIUM_MULTIPLIER", 1.0, 10.0, 2.0983606207319, float, 1.0),
    ("DEEP_PERIOD_TIER_HEAVY_MULTIPLIER", 1.0, 20.0, 3.2036101139833, float, 1.0),
]

# PARAMETER_MAPPING maps each SPSA parameter to (C_filepath, C_variable_name, type)
PARAMETER_MAPPING = {
    # ROUTING
    "ROUTING_SHALLOW_RATIO": ("src/params_double.c", "g_routing_shallow_ratio", "double"),
    "ROUTING_MEDIUM_RATIO": ("src/params_double.c", "g_routing_medium_ratio", "double"),
    "GLOBAL_ENTROPY_UNSET_BIAS": ("src/params_double.c", "g_global_entropy_unset_bias", "double"),
    # ROOT
    "ROOT_MIN_ENTROPY": ("src/params_int.c", "g_root_min_entropy", "int"),
    "ROOT_GAC_MIN_ENTROPY": ("src/params_int.c", "g_root_gac_min_entropy", "int"),
    "ROOT_CONSTR_MIN_ENTROPY": ("src/params_int.c", "g_root_constr_min_entropy", "int"),
    "ROOT_PERIOD_COEF_SCALE": ("src/params_double.c", "g_root_period_coef_scale", "double"),
    "ROOT_PERIOD_COEF_UNSET": ("src/params_double.c", "g_root_period_coef_unset", "double"),
    # SHALLOW
    "SHALLOW_MIN_ENTROPY": ("src/params_int.c", "g_shallow_min_entropy", "int"),
    "SHALLOW_GAC_MIN_ENTROPY": ("src/params_int.c", "g_shallow_gac_min_entropy", "int"),
    "SHALLOW_CONSTR_MIN_ENTROPY": ("src/params_int.c", "g_shallow_constr_min_entropy", "int"),
    "SHALLOW_PERIOD_COEF_SCALE": ("src/params_double.c", "g_shallow_period_coef_scale", "double"),
    "SHALLOW_PERIOD_COEF_UNSET": ("src/params_double.c", "g_shallow_period_coef_unset", "double"),
    # MEDIUM
    "MEDIUM_MIN_ENTROPY": ("src/params_int.c", "g_medium_min_entropy", "int"),
    "MEDIUM_GAC_MIN_ENTROPY": ("src/params_int.c", "g_medium_gac_min_entropy", "int"),
    "MEDIUM_CONSTR_MIN_ENTROPY": ("src/params_int.c", "g_medium_constr_min_entropy", "int"),
    "MEDIUM_PERIOD_COEF_SCALE": ("src/params_double.c", "g_medium_period_coef_scale", "double"),
    "MEDIUM_PERIOD_COEF_UNSET": ("src/params_double.c", "g_medium_period_coef_unset", "double"),
    # DEEP
    "DEEP_MIN_ENTROPY": ("src/params_int.c", "g_deep_min_entropy", "int"),
    "DEEP_GAC_MIN_ENTROPY": ("src/params_int.c", "g_deep_gac_min_entropy", "int"),
    "DEEP_CONSTR_MIN_ENTROPY": ("src/params_int.c", "g_deep_constr_min_entropy", "int"),
    "DEEP_PERIOD_COEF_SCALE": ("src/params_double.c", "g_deep_period_coef_scale", "double"),
    "DEEP_PERIOD_COEF_UNSET": ("src/params_double.c", "g_deep_period_coef_unset", "double"),
    # SELECTIVITY
    "SEL_PERIOD_COEF_SQRT": ("src/params_double.c", "g_sel_period_coef_sqrt", "double"),
    "SEL_PERIOD_COEF_INV": ("src/params_double.c", "g_sel_period_coef_inv", "double"),
    # LOOKAHEAD DOWNGRADE FRACTIONS
    "ROOT_LOOKAHEAD_DOWNGRADE_FRACTION": ("src/params_double.c", "g_root_lookahead_downgrade_fraction", "double"),
    "SHALLOW_LOOKAHEAD_DOWNGRADE_FRACTION": ("src/params_double.c", "g_shallow_lookahead_downgrade_fraction", "double"),
    "MEDIUM_LOOKAHEAD_DOWNGRADE_FRACTION": ("src/params_double.c", "g_medium_lookahead_downgrade_fraction", "double"),
    "DEEP_LOOKAHEAD_DOWNGRADE_FRACTION": ("src/params_double.c", "g_deep_lookahead_downgrade_fraction", "double"),
    # ROOT LOCAL/GLOBAL BOUNDS
    "ROOT_GAC_LOCAL_MIN_ENTROPY": ("src/params_double.c", "g_root_gac_local_min_entropy", "double"),
    "ROOT_GAC_LOCAL_MAX_ENTROPY": ("src/params_double.c", "g_root_gac_local_max_entropy", "double"),
    "ROOT_GAC_GLOBAL_MIN_ENTROPY": ("src/params_int.c", "g_root_gac_global_min_entropy", "int"),
    "ROOT_CONSTR_LOCAL_MIN_ENTROPY": ("src/params_double.c", "g_root_constr_local_min_entropy", "double"),
    "ROOT_CONSTR_LOCAL_MAX_ENTROPY": ("src/params_double.c", "g_root_constr_local_max_entropy", "double"),
    "ROOT_CONSTR_GLOBAL_MIN_ENTROPY": ("src/params_int.c", "g_root_constr_global_min_entropy", "int"),
    "ROOT_LOOKAHEAD_GAC_LOCAL_MIN_ENTROPY": ("src/params_double.c", "g_root_lookahead_gac_local_min_entropy", "double"),
    "ROOT_LOOKAHEAD_GAC_LOCAL_MAX_ENTROPY": ("src/params_double.c", "g_root_lookahead_gac_local_max_entropy", "double"),
    "ROOT_LOOKAHEAD_GAC_GLOBAL_MIN_ENTROPY": ("src/params_int.c", "g_root_lookahead_gac_global_min_entropy", "int"),
    "ROOT_LOOKAHEAD_CONSTR_LOCAL_MIN_ENTROPY": ("src/params_double.c", "g_root_lookahead_constr_local_min_entropy", "double"),
    "ROOT_LOOKAHEAD_CONSTR_LOCAL_MAX_ENTROPY": ("src/params_double.c", "g_root_lookahead_constr_local_max_entropy", "double"),
    "ROOT_LOOKAHEAD_CONSTR_GLOBAL_MIN_ENTROPY": ("src/params_int.c", "g_root_lookahead_constr_global_min_entropy", "int"),
    # SHALLOW LOCAL/GLOBAL BOUNDS
    "SHALLOW_GAC_LOCAL_MIN_ENTROPY": ("src/params_double.c", "g_shallow_gac_local_min_entropy", "double"),
    "SHALLOW_GAC_LOCAL_MAX_ENTROPY": ("src/params_double.c", "g_shallow_gac_local_max_entropy", "double"),
    "SHALLOW_GAC_GLOBAL_MIN_ENTROPY": ("src/params_int.c", "g_shallow_gac_global_min_entropy", "int"),
    "SHALLOW_CONSTR_LOCAL_MIN_ENTROPY": ("src/params_double.c", "g_shallow_constr_local_min_entropy", "double"),
    "SHALLOW_CONSTR_LOCAL_MAX_ENTROPY": ("src/params_double.c", "g_shallow_constr_local_max_entropy", "double"),
    "SHALLOW_CONSTR_GLOBAL_MIN_ENTROPY": ("src/params_int.c", "g_shallow_constr_global_min_entropy", "int"),
    "SHALLOW_LOOKAHEAD_GAC_LOCAL_MIN_ENTROPY": ("src/params_double.c", "g_shallow_lookahead_gac_local_min_entropy", "double"),
    "SHALLOW_LOOKAHEAD_GAC_LOCAL_MAX_ENTROPY": ("src/params_double.c", "g_shallow_lookahead_gac_local_max_entropy", "double"),
    "SHALLOW_LOOKAHEAD_GAC_GLOBAL_MIN_ENTROPY": ("src/params_int.c", "g_shallow_lookahead_gac_global_min_entropy", "int"),
    "SHALLOW_LOOKAHEAD_CONSTR_LOCAL_MIN_ENTROPY": ("src/params_double.c", "g_shallow_lookahead_constr_local_min_entropy", "double"),
    "SHALLOW_LOOKAHEAD_CONSTR_LOCAL_MAX_ENTROPY": ("src/params_double.c", "g_shallow_lookahead_constr_local_max_entropy", "double"),
    "SHALLOW_LOOKAHEAD_CONSTR_GLOBAL_MIN_ENTROPY": ("src/params_int.c", "g_shallow_lookahead_constr_global_min_entropy", "int"),
    # MEDIUM LOCAL/GLOBAL BOUNDS
    "MEDIUM_GAC_LOCAL_MIN_ENTROPY": ("src/params_double.c", "g_medium_gac_local_min_entropy", "double"),
    "MEDIUM_GAC_LOCAL_MAX_ENTROPY": ("src/params_double.c", "g_medium_gac_local_max_entropy", "double"),
    "MEDIUM_GAC_GLOBAL_MIN_ENTROPY": ("src/params_int.c", "g_medium_gac_global_min_entropy", "int"),
    "MEDIUM_CONSTR_LOCAL_MIN_ENTROPY": ("src/params_double.c", "g_medium_constr_local_min_entropy", "double"),
    "MEDIUM_CONSTR_LOCAL_MAX_ENTROPY": ("src/params_double.c", "g_medium_constr_local_max_entropy", "double"),
    "MEDIUM_CONSTR_GLOBAL_MIN_ENTROPY": ("src/params_int.c", "g_medium_constr_global_min_entropy", "int"),
    "MEDIUM_LOOKAHEAD_GAC_LOCAL_MIN_ENTROPY": ("src/params_double.c", "g_medium_lookahead_gac_local_min_entropy", "double"),
    "MEDIUM_LOOKAHEAD_GAC_LOCAL_MAX_ENTROPY": ("src/params_double.c", "g_medium_lookahead_gac_local_max_entropy", "double"),
    "MEDIUM_LOOKAHEAD_GAC_GLOBAL_MIN_ENTROPY": ("src/params_int.c", "g_medium_lookahead_gac_global_min_entropy", "int"),
    "MEDIUM_LOOKAHEAD_CONSTR_LOCAL_MIN_ENTROPY": ("src/params_double.c", "g_medium_lookahead_constr_local_min_entropy", "double"),
    "MEDIUM_LOOKAHEAD_CONSTR_LOCAL_MAX_ENTROPY": ("src/params_double.c", "g_medium_lookahead_constr_local_max_entropy", "double"),
    "MEDIUM_LOOKAHEAD_CONSTR_GLOBAL_MIN_ENTROPY": ("src/params_int.c", "g_medium_lookahead_constr_global_min_entropy", "int"),
    # DEEP LOCAL/GLOBAL BOUNDS
    "DEEP_GAC_LOCAL_MIN_ENTROPY": ("src/params_double.c", "g_deep_gac_local_min_entropy", "double"),
    "DEEP_GAC_LOCAL_MAX_ENTROPY": ("src/params_double.c", "g_deep_gac_local_max_entropy", "double"),
    "DEEP_GAC_GLOBAL_MIN_ENTROPY": ("src/params_int.c", "g_deep_gac_global_min_entropy", "int"),
    "DEEP_CONSTR_LOCAL_MIN_ENTROPY": ("src/params_double.c", "g_deep_constr_local_min_entropy", "double"),
    "DEEP_CONSTR_LOCAL_MAX_ENTROPY": ("src/params_double.c", "g_deep_constr_local_max_entropy", "double"),
    "DEEP_CONSTR_GLOBAL_MIN_ENTROPY": ("src/params_int.c", "g_deep_constr_global_min_entropy", "int"),
    "DEEP_LOOKAHEAD_GAC_LOCAL_MIN_ENTROPY": ("src/params_double.c", "g_deep_lookahead_gac_local_min_entropy", "double"),
    "DEEP_LOOKAHEAD_GAC_LOCAL_MAX_ENTROPY": ("src/params_double.c", "g_deep_lookahead_gac_local_max_entropy", "double"),
    "DEEP_LOOKAHEAD_GAC_GLOBAL_MIN_ENTROPY": ("src/params_int.c", "g_deep_lookahead_gac_global_min_entropy", "int"),
    "DEEP_LOOKAHEAD_CONSTR_LOCAL_MIN_ENTROPY": ("src/params_double.c", "g_deep_lookahead_constr_local_min_entropy", "double"),
    "DEEP_LOOKAHEAD_CONSTR_LOCAL_MAX_ENTROPY": ("src/params_double.c", "g_deep_lookahead_constr_local_max_entropy", "double"),
    "DEEP_LOOKAHEAD_CONSTR_GLOBAL_MIN_ENTROPY": ("src/params_int.c", "g_deep_lookahead_constr_global_min_entropy", "int"),
    # TIER MULTIPLIERS
    "ROOT_PERIOD_TIER_MEDIUM_MULTIPLIER": ("src/params_double.c", "g_root_period_tier_medium_mult", "double"),
    "ROOT_PERIOD_TIER_HEAVY_MULTIPLIER": ("src/params_double.c", "g_root_period_tier_heavy_mult", "double"),
    "SHALLOW_PERIOD_TIER_MEDIUM_MULTIPLIER": ("src/params_double.c", "g_shallow_period_tier_medium_mult", "double"),
    "SHALLOW_PERIOD_TIER_HEAVY_MULTIPLIER": ("src/params_double.c", "g_shallow_period_tier_heavy_mult", "double"),
    "MEDIUM_PERIOD_TIER_MEDIUM_MULTIPLIER": ("src/params_double.c", "g_medium_period_tier_medium_mult", "double"),
    "MEDIUM_PERIOD_TIER_HEAVY_MULTIPLIER": ("src/params_double.c", "g_medium_period_tier_heavy_mult", "double"),
    "DEEP_PERIOD_TIER_MEDIUM_MULTIPLIER": ("src/params_double.c", "g_deep_period_tier_medium_mult", "double"),
    "DEEP_PERIOD_TIER_HEAVY_MULTIPLIER": ("src/params_double.c", "g_deep_period_tier_heavy_mult", "double"),
}

# PARAM_CONSTRAINTS defines linear constraints between parameters.
# Format: (param_min_name, param_max_name, eps)
# enforces: physical_value(param_min_name) <= physical_value(param_max_name) + eps
PARAM_CONSTRAINTS = [
    # ROOT
    ("ROOT_GAC_LOCAL_MIN_UNSET", "ROOT_GAC_LOCAL_MAX_UNSET", 0.05),
    ("ROOT_CONSTR_LOCAL_MIN_UNSET", "ROOT_CONSTR_LOCAL_MAX_UNSET", 0.05),
    ("ROOT_LOOKAHEAD_GAC_LOCAL_MIN_UNSET", "ROOT_LOOKAHEAD_GAC_LOCAL_MAX_UNSET", 0.05),
    ("ROOT_LOOKAHEAD_CONSTR_LOCAL_MIN_UNSET", "ROOT_LOOKAHEAD_CONSTR_LOCAL_MAX_UNSET", 0.05),
    # SHALLOW
    ("SHALLOW_GAC_LOCAL_MIN_UNSET", "SHALLOW_GAC_LOCAL_MAX_UNSET", 0.05),
    ("SHALLOW_CONSTR_LOCAL_MIN_UNSET", "SHALLOW_CONSTR_LOCAL_MAX_UNSET", 0.05),
    ("SHALLOW_LOOKAHEAD_GAC_LOCAL_MIN_UNSET", "SHALLOW_LOOKAHEAD_GAC_LOCAL_MAX_UNSET", 0.05),
    ("SHALLOW_LOOKAHEAD_CONSTR_LOCAL_MIN_UNSET", "SHALLOW_LOOKAHEAD_CONSTR_LOCAL_MAX_UNSET", 0.05),
    # MEDIUM
    ("MEDIUM_GAC_LOCAL_MIN_UNSET", "MEDIUM_GAC_LOCAL_MAX_UNSET", 0.05),
    ("MEDIUM_CONSTR_LOCAL_MIN_UNSET", "MEDIUM_CONSTR_LOCAL_MAX_UNSET", 0.05),
    ("MEDIUM_LOOKAHEAD_GAC_LOCAL_MIN_UNSET", "MEDIUM_LOOKAHEAD_GAC_LOCAL_MAX_UNSET", 0.05),
    ("MEDIUM_LOOKAHEAD_CONSTR_LOCAL_MIN_UNSET", "MEDIUM_LOOKAHEAD_CONSTR_LOCAL_MAX_UNSET", 0.05),
    # DEEP
    ("DEEP_GAC_LOCAL_MIN_UNSET", "DEEP_GAC_LOCAL_MAX_UNSET", 0.05),
    ("DEEP_CONSTR_LOCAL_MIN_UNSET", "DEEP_CONSTR_LOCAL_MAX_UNSET", 0.05),
    ("DEEP_LOOKAHEAD_GAC_LOCAL_MIN_UNSET", "DEEP_LOOKAHEAD_GAC_LOCAL_MAX_UNSET", 0.05),
    ("DEEP_LOOKAHEAD_CONSTR_LOCAL_MIN_UNSET", "DEEP_LOOKAHEAD_CONSTR_LOCAL_MAX_UNSET", 0.05),
]
